// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZCzpq1k8TTTckXkRy0SQIWWQWW8jWKx8',
    appId: '1:477759067010:web:e7898c8351570ebba3759b',
    messagingSenderId: '477759067010',
    projectId: 'moneymanager-ab06d',
    authDomain: 'moneymanager-ab06d.firebaseapp.com',
    storageBucket: 'moneymanager-ab06d.appspot.com',
    measurementId: 'G-8X2PM3YN5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Pq0-EMqciUFL7L8TRyQ6toAfMXE4dvY',
    appId: '1:477759067010:android:c8c8554fec8f28eda3759b',
    messagingSenderId: '477759067010',
    projectId: 'moneymanager-ab06d',
    storageBucket: 'moneymanager-ab06d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgb2O6ZFyi_0wkhyCL8p7yuA-KP-SzAf0',
    appId: '1:477759067010:ios:0e19718fe8a44a34a3759b',
    messagingSenderId: '477759067010',
    projectId: 'moneymanager-ab06d',
    storageBucket: 'moneymanager-ab06d.appspot.com',
    iosClientId: '477759067010-qffmtflq00r7sjgk3949mf1jvl1po9f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyManager',
  );
}
